apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: bookapi
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: bookapi
        tier: backend
    spec:
      containers:
        - name: app
          image: emirozbir/bookapi:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
