apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: nginx
        tier: frontend
    spec:
      containers:
        - name: nginx
          image: nginx:1.13.0-alpine
          ports:
            - containerPort: 80
            - containerPort: 443
          volumeMounts:
            - name: secrets-volume
              mountPath: /etc/nginx/ssl
              readOnly: true
            - name: configmap-volume
              mountPath: /etc/nginx/conf.d
              readOnly: true
      volumes:
        - name: secrets-volume
          secret:
            secretName: nginx
        - name: configmap-volume
          configMap:
            name: nginx
